### ISSUE TITLE
Say 'Hi everyone'

### ISSUE THREAD

**Issue by shreyateeza** [Novice-Paradigm/Ruby#1]
## Description
Write 'Hi everyone' in Ruby.

**Comment by conradwt** [comment]
I was wondering, are you looking for a Rails app or a Ruby app here?  I was thinking that you were looking for a Rails app from the title of the repository.

**Comment by rishiip** [comment]
@conradwt Thanks for showing interest in ruby on rails. This repository focuses on ruby language only. We'll update description soon.
